apiVersion: v1
kind: Service
services:
  - type: web
    name: hotelapp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn hotelmgt.wsgi:application --bind 0.0.0.0:8000"
    port: 8000