apiVersion: v1
kind: Service
services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn your_application.wsgi:application --bind 0.0.0.0:8000"
