# Generated by Django 5.1.7 on 2025-03-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'Mpesa'), ('card', 'Debit Card')], default='mpesa', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
